### ISSUE TITLE
[BUG] deserialization of tuples

### ISSUE THREAD

**Issue by andreim14** [andreim14/beanis#1]
**Describe the bug**
Problem when deserializing dictionaries that have tuples as keys. They are serialized as strings but when deserializing the library crashes.

**To Reproduce**
```python
import asyncio
from typing import Optional, Dict, Tuple

from redis import Redis
from pydantic import BaseModel

from beanis import Document, init_beanis


class Product(Document):
    attributes: Dict[Tuple[int, int], str]  # Field with a dictionary that has tuples as keys and strings as values


# This is an asynchronous example, so we will access it from an async function
async def example():
    # Beanis uses Redis async client under the hood
    client = Redis(host="localhost", port=6379, db=0, decode_responses=True)

    # Initialize beanis with the Product document class
    await init_beanis(database=client, document_models=[Product])
    
    # Create a product with attributes field
    tonybar = Product(
        id="unique_magic_id",
        attributes={(1, 2): "Value1", (3, 4): "Value2"}
    )
    # And can be inserted into the database
    await tonybar.insert()

    # You can find documents by their unique id
    product = await Product.find("unique_magic_id")
    print(product)


if __name__ == "__main__":
    asyncio.run(example())
```

**Expected behavior**
Should correctly deserialize

**Additional context**
```
Traceback (most recent call last):
  File "/path/to/project/test.py", line 37, in <module>
    asyncio.run(example())
  File "/path/to/python/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/path/to/python/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/path/to/project/test.py", line 32, in example
    product = await Product.find("unique_magic_id")
  File "/path/to/project/odm/documents.py", line 159, in find
    return await cls.get(document_id=document_id)
  File "/path/to/project/odm/documents.py", line 154, in get
    return cast(type(cls_loaded), parse_obj(cls_loaded, loaded_data))
  File "/path/to/project/odm/utils/parsing.py", line 146, in parse_obj
    result = parse_model(model, data)
  File "/path/to/project/odm/utils/pydantic.py", line 37, in parse_model
    return model_type.model_validate(data)
  File "/path/to/python/site-packages/pydantic/main.py", line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Product
attributes.(1, 2).[key]
  Input should be a valid tuple [type=tuple_type, input_value='(1, 2)', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/tuple_type
attributes.(3, 4).[key]
  Input should be a valid tuple [type=tuple_type, input_value='(3, 4)', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/tuple_type
```

**Comment by andreim14** [comment]
solved with new update
